### ISSUE TITLE
Add the ability to generate passwords

### ISSUE THREAD

**Issue by tdb** [1Password/onepassword-sdk-python#105]
### Use Case

I have a tool for rotating passwords. It updates the password in 1Password and then on the system. I've used the Connect API with its `generate` and `recipe` fields to do this before, and the CLI has the `--generate-password[=recipe]` flag to do the same. I could generate passwords in my tool, but I'd prefer to continue with 1Password doing this for me all in one step.

### Requirements and desired behavior

I suppose the most consistent way would be to do similar to how the [Connect API](https://developer.1password.com/docs/connect/connect-api-reference/#add-an-item) does it. Make the value field optional for password items, and have a boolean generate field and optional recipe field.

**Comment by hculea** [comment]
@tdb we've just released 0.1.5 which adds the ability to generate passwords. I'll be closing this ticket, please reopen if needed! Thanks for the feature request 💙
