### ISSUE TITLE
Username missing from item preview card 

### ISSUE THREAD

**Issue by jessewindebank1809** [1Password/onepassword-sdk-python#118]
### Scenario & Reproduction Steps

When creating a new item using the onepassword python SDK, the item preview card does not preview the stored username. Instead, it just puts _

Here is the code snippet in case the code is incorrect:
![2024-09-24 at 13 52 06](https://github.com/user-attachments/assets/d74beb60-0b4f-41d8-856b-e1539175110a)

### Actual Behavior

![2024-09-24 at 13 37 48](https://github.com/user-attachments/assets/7a060a3d-1e75-4636-ac69-020672b81f4e)

Here is the value within the item detail card:
![2024-09-24 at 13 38 05](https://github.com/user-attachments/assets/6a8d871a-4385-4ae2-887d-efe448fc7aa4)

### Expected Behavior

I am expecting to see this:
![2024-09-24 at 14 02 52](https://github.com/user-attachments/assets/35aece29-a915-42b0-8bcb-0946aa6002d8)

### SDK version

0.1.1

**Comment by hculea** [comment]
Hi @jessewindebank1809 , thank you for reporting this! 

I am going to file a bug internally for us to track this. Can you please let me know what the urgency of this is for you? Are you relying on the subtitles in one of your workflows, or is this more so of an issue of consistency across 1Password clients? Thanks!

**Comment by jessewindebank1809** [comment]
Hi @hculea 

This is a low priority but wanted to raise it so you were aware. 

Thanks for raising this internally.

**Comment by hculea** [comment]
@jessewindebank1809 this should now be fixed in v0.1.5 which we just released today.

Please feel free to reopen the ticket if you run into this again 💙
