### ISSUE TITLE
Use correct request library in Python SDK defaults

### ISSUE THREAD

**Issue by hculea** [1Password/onepassword-sdk-python#37]
https://github.com/1Password/onepassword-sdk-python/blob/main/src/onepassword/defaults.py#L7

This has been copied from the Go SDK. The Python SDK core relies on the http client from Rust, so the correct value for this value should be `reqwest`.

**Comment by AndyTitu** [comment]
And we should make sure we note the version of reqwest we use in sdk-core as well
