### ISSUE TITLE
Feature request: A method to load all sections or fields in an item

### ISSUE THREAD

**Issue by ShravanSunder** [1Password/onepassword-sdk-python#56]
It would be much easier to load data for a .env file if we could load all the fiends in a section/item with a single service account call.  

We could use this to populate a dict for dot env variables.  I would find this much easier to use.  i'd also like to request this for the https://github.com/1Password/onepassword-sdk-js library as well

![2024-06-15 0633 Brave Browser Use secret references with 1Password CLI  1Password Developer](https://github.com/1Password/onepassword-sdk-python/assets/5294949/3e63e5c7-e69d-4170-8472-30db58de0b43)

**Comment by SimonBarendse** [comment]
Closing with same resolution as https://github.com/1Password/onepassword-sdk-js/issues/52
