### ISSUE TITLE
Support URLs

### ISSUE THREAD

**Issue by jessewindebank1809** [1Password/onepassword-sdk-python#57]
Please add URLs to the item get and update methods.

We are a power user of the Connect SDK and would need this capability to look at moving across to this new SDK.

Moving away from hosting own infra to run Connect has huge appeal.

**Comment by Marton6** [comment]
Hey @jessewindebank1809.

Thanks for sharing your use-case for the 1Password SDKs!

We'll look into adding support for URLs in future versions of the SDKs

**Comment by SimonBarendse** [comment]
Closing this ticket since support for URL fields was added since [v0.1.0-beta.12](https://github.com/1Password/onepassword-sdk-python/releases/tag/v0.1.0-beta.12).

**Comment by SimonBarendse** [comment]
@jessewindebank1809 quick note that unfortunately URL type fields are separate from the built-in website field on Login items. The built-in website field on Login items is not _yet_ supported. Would you need support for that too? If so, could you file another issue for that?
