### ISSUE TITLE
Add support for OTP fields

### ISSUE THREAD

**Issue by pmareke** [1Password/onepassword-sdk-python#59]
First of all thanks for your time, the SDK is really helpful!

I've just realised that it's not possible to retrieve a temporal OTP code from a vault.

If you use the items `get` method the field is `Unsupported` and it comes empty.

```
ItemField(id='TOTP_esfogadaary7lfnv4nflwzzr2e', title='one-time password', section_id=None, field_type='Unsupported', value='')
```

If you use the secrets `resolve` method it returns the raw value of the OTP code but not the code itself.

**Comment by pmareke** [comment]
Thanks @Marton6, if I can give a hand I would love to help!

**Comment by simkimsia** [comment]
Please support this. This was the primary reason why i experimented with this sdk. Not having this means I have to stop my experimentation.

**Comment by MOmarMiraj** [comment]
Hey @pmareke and @simkimsia

With the latest releases of the Python SDK (v0.1.0-beta.12+) you are now able to read and write OTP field information.

If you have any other issues with this, please feel free to open another issue.
