### ISSUE TITLE
Cant resolve Secret reference with a dot "." in it's name.

### ISSUE THREAD

**Issue by jcphlux** [1Password/onepassword-sdk-python#75]
### Scenario & Reproduction Steps

Was getting an error:
`error resolving secret reference: secret reference has invalid format - must be "op://<vault>/<item>/[section/]field"`
I had folled the steps in https://developer.1password.com/docs/cli/secret-reference-syntax/ to get the secret reference so I knew it was correct.

I created a duplicate of the item in my vault and removed the dot "." from the name and it was able to retrive the item without an error.

### Actual Behavior

 not retriving values of items with a dot "." in there name.

### Expected Behavior

Retriving values of items no mater what the item name is.

### SDK version

CLI 2.29.0,  pip v0.1.0-beta.11

**Comment by MOmarMiraj** [comment]
Hi @jcphlux 

With the latest version of the Python SDK (v0.1.0-beta.12+), this bug has been fixed and you can now resolve secret references with `.` in the name.

If you have any issues with the latest versions of the SDK, please feel free to open another issue.
