### ISSUE TITLE
pip install beta.11 gives me beta.10

### ISSUE THREAD

**Issue by simkimsia** [1Password/onepassword-sdk-python#80]
### Scenario & Reproduction Steps

pip install --upgrade git+ssh://git@github.com/1Password/onepassword-sdk-python.git@v0.1.0-beta.11

then 

pip list | grep onepassword

### Actual Behavior

i get back 

> pip list | grep onepassword
onepassword       0.1.0b10

### Expected Behavior

> pip list | grep onepassword
onepassword       0.1.0b11

**Comment by Marton6** [comment]
Hey @simkimsia! Thank you for reporting this. I can reproduce this issue. We will look into fixing it soon.

**Comment by simkimsia** [comment]
think this is fixed. since now 0.1.1
